image: $CI_REGISTRY/ci-images/haskell:latest

stages:
  - build

build:default:
  stage: build
  variables:
    ARTIFACT_URL: $CI_PROJECT_URL/builds/$CI_JOB_ID/artifacts/download
  script:
    - stack build
    - mkdir build
    - mv $(stack path --local-install-root)/bin/* build/
    - upx --best build/*
  artifacts:
    expire_in: 1 week
    paths:
      - build/*

cache:
  paths:
    - .stack-work

