image: haskell:latest

stages:
  - build

build:default:
  stage: build
  variables:
    ARTIFACT_URL: $CI_PROJECT_URL/builds/$CI_JOB_ID/artifacts/download
  script:
    - apt-get update && apt-get install -y build-essential
    - stack setup
    - stack update
    - stack build
  artifacts:
    expire_in: 1 week
    paths:
      - build/*

